FROM airhacks/wildfly
COPY ./target/maxcube-web.war ${DEPLOYMENT_DIR}
ENV EQ3_HOST=192.168.178.28

# docker exec -i -t micro /bin/bash
# tail -f /opt/wildfly-11.0.0.Final/standalone/log/server.log
# OR
# docker logs micro
